Update frontend.yml

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -17,14 +17,13 @@ jobs:
         uses: oven-sh/setup-bun@v2
       - name: Install dependencies
         run: bun install
-      - name: Make folder
-        run: mkdir ci
       - name: Run lints
-        run: bunx biome ci --reporter=junit > ./ci/lints.xml
+        run: bunx biome ci
       # - name: Run tests
-      #   run: bun test --reporter=junit --reporter-outfile=./ci/tests.xml
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v5
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: '**/ci/*.xml'
+      #   run: bun test
+      # - name: Publish Test Report
+      #   uses: mikepenz/action-junit-report@v5
+      #   if: success() || failure() # always run even if the previous step fails
+      #   with:
+      #     report_paths: '**/ci/*.xml'
+      
